zuul:
  routes:
    account-service:
      path: /account/**
      #serviceId: account-service
      stripPrefix: false
    authentication-service:
      path: /login/**
  sensitive-headers:
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone : http://${eureka.instance.hostname}:8761/eureka/

  server:
    eviction-interval-timer-in-ms: 1000
spring:
  application:
    name: zuul-service
#account-service:
#  ribbon:
#    listOfServers: http://localhost:8383, http://localhost:8989

